[project]
name = "xxx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "ebooklib>=0.18",
    "kokoro-onnx>=0.3.3",
    "sounddevice>=0.5.1",
    "soundfile>=0.13.0",
]
