[project]
name = "xxx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "ebooklib>=0.18",
    "kokoro-onnx[gpu]>=0.3.3",
    "sounddevice>=0.5.1",
    "soundfile>=0.13.0",
]
